openapi: 3.0.0
info:
  title: Master-Data-Service
  description: ""
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/rushang.dhanesha/Master-Data-Service/1.0.0
  description: SwaggerHub API Auto Mocking
paths: {}
components: {}
